version: '3.8'

services:
  lakeside-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lakeside-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local