services:
  lakeside-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PHONE: ${NEXT_PUBLIC_PHONE}
        NEXT_PUBLIC_PHONE_LINK: ${NEXT_PUBLIC_PHONE_LINK}
        NEXT_PUBLIC_EMAIL: ${NEXT_PUBLIC_EMAIL}
        NEXT_PUBLIC_YANDEX_METRICA_ID: ${NEXT_PUBLIC_YANDEX_METRICA_ID}
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL}
        NEXT_PUBLIC_PHOTO_DRIVE_URL: ${NEXT_PUBLIC_PHOTO_DRIVE_URL}
    container_name: lakeside-app
    restart: unless-stopped
    ports:
      - "8081:3000"
    env_file:
      - .env